litex-hub/litespi

litespi/clkgen.py, litespi/phy/generic.py
This PR mainly adds support for the DDR mode of operation where address and data is transferred on both edges of the clock. This has only been tested in `litex_sim` but the resulting timing diagrams seem to match ones in `S25FL128S` datasheet which I used as a reference on DDR transfers in SPI flashes.
Other minor changes are:
- Added support for octal mode chips.
- Clkgen posedge & negedge are now asserted in the cycle in which the `clk` value changes and not in the one after that.
- Command & address register indexing has been simplified.
- Cleaned up `shift_out` method.
=> Add support for DDR transfers & minor fixes

litespi/modules/generated_modules.py, litespi/modules/modules.py, litespi/opcodes.py, litespi/spi_nor_features.py, litespi/spi_nor_flash_module.py, tools/spi_nor_config_generator/flash_module_template.py, tools/spi_nor_config_generator/override_cfg.py, tools/spi_nor_config_generator/spi_nor_cfg_gen.py
I reworked code around configuring chips into desired mode and chips capabilities. In the result instead of a config which contains a lot of flags from _SpiNorFeatures_, we can simply pass a read command, which contains all the required info to configure a chip into a selected mode.
List of major changes:
- _litespi.modules_ have now a list of supported commands (READ and PP) instead of _SpiNorFeatures_ flags.
- Configuring a chip is done simply by passing read opcode e.g.: `GD25Q256(read_cmd=SpiNorFlashOpCodes.READ_1_1_4_4B)`
- reverted _SpiNorFeatures_ to the original state (reverted flags such as FEATURE_SINGLE/DUAL etc.)
- I unified some names in _SpiNorFlashOpCodes_ to be able to parse them
@mithro please take a look
=> Rework configuring chips using opcodes

litespi/phy/generic.py
Set `dummy_bits` to `0` when `fast_mode` is not enabled otherwise use `flash.dummy_bits` field.
=> litespi/phy/generic: setup dummy_bits according to fast_mode

litespi/clkgen.py, litespi/phy/generic.py, litespi/spi_nor_flash_module.py
This PR improves the clock generation logic in `Clkgen`, replaces `TSTriple` with `SDRTristate` in generic PHY and fixes two small issues that I encountered while testing this on HW(configurations without dummy bits were not working correctly and it was impossible to commands not utilizing full potential of the SPI bus ie. fast read on pinout that supports quad)
Closes #18
=> Improved clocking

litespi/modules/modules.py
Fixes #17 
Docs: [MX25L6406E](https://www.macronix.com/Lists/Datasheet/Attachments/7370/MX25L6406E,%203V,%2064Mb,%20v1.9.pdf), [W25Q512JV](https://www.winbond.com/resource-files/W25Q512JV%20SPI%20RevB%2006252019%20KMS.pdf)
=> litespi/modules: add MX25L6406E and W25Q512JV to non-generated modules

litespi/clkgen.py
The issue was non-delayed signals in clkgen which are needed when we use SDRTristate.
PR adds changes which delay clkgen signals by 1 cycle.
Closes #32
=> litespi: delay signals in clkgen by 1 cycle due to usage of SDRTristate

litespi/__init__.py, litespi/phy/generic.py
PR adds CSRs for clkdiv and dummy bits to configure them from e.g. BIOS.
Additionally I added a CSR status to store sys clk frequency - this is used only to calculate frequency during runtime.
=> Add clkdiv and dummybits CSRs

litespi/phy/generic.py
=> litespi/phy: add default dummy bits handling for I/O and DTR modes

examples/arty.py, litespi/__init__.py, litespi/crossbar.py, litespi/phy/generic.py
This PR introduces changes which give a possibility to have LiteSPI in a separate clock domain.
The only doubt I have is do we have to pipeline the data from CSRs (which are in sys clock domain) to litespi clock domain using e.g. AsynFIFOs? I mean these [registers](https://github.com/litex-hub/litespi/pull/38/files#diff-76745ba1ce398bffc095fd8450e49fcdL51-L52). I tested on Arty board two configurations:
- LiteSPI in `sys` clock domain
- LiteSPI in `clk200` clock domain
in each cases I was able to successfully read from flash.
Closes #23
=> Add optional litespi wrapping into separate clock domain

.gitignore, examples/colorlight.py, litespi/clkgen.py
This PR includes support for the USRMCLK instance in clkgen.py and provides an example for the Colorlight 5A-75E. It borrows heavily from [examples/arty.py](https://github.com/litex-hub/litespi/blob/master/examples/arty.py) and [enjoy-digital/colorlite.py](https://github.com/enjoy-digital/colorlite/blob/master/colorlite.py).
Fixes #40
=> ECP5 support and Colorlight example.

litespi/phy/generic.py
SyntaxWarning: "is not" with a literal. Did you mean "!="
=> Fix Python >= 3.8  SyntaxWarning

litespi/__init__.py, litespi/common.py, litespi/core/master.py, litespi/core/mmap.py, litespi/crossbar.py, litespi/phy/generic.py, litespi/phy/model.py
This patchset implements #46.
Arbitration is handled with a `request` signal that's by default derived from CS, but overridable for modules that needs to keep uninterrupted control across multiple commands.
To allow the MMIO core to still merge sequential reads into a single command but also allow other cores to use the flash, I've added a timeout for how long it'll keep CS asserted after a finished read. The performance overhead from the 10000-cycle CS delay (see #43) will be addressed in a later PR.
I've also included two patches that cleans up the CS polarity and fixes the remaining erroneous uses of `is not`.
Since the CSR for manual mode control is removed, this PR depends on https://github.com/enjoy-digital/litex/pull/915 also being merged.
Closes #46.
=> Add arbitration

litespi/core/mmap.py, litespi/phy/generic.py
This patch removes the CS delay from the MMAP module and adds enforcement of a minimum CS inactive time to the PHY instead. This will ensure it is enforced regardless of which module is accessing the flash.
I haven't seen any rationale for why the default should be 10000 cycles, so I've reduced it to 10, which seems plenty for typical flash chips and system frequencies. If the default is not appropriate, it's now also configurable through an argument to the PHY.
In the future we should probably add the minimum time to the module metadata so that the minimum number of cycles can be calculated rather than configured, but that is out of the scope for this PR.
Fixes #43.
=> phy/generic: Enforce minimum CS inactive time.

litespi/phy/generic.py
If `LiteSPIPHY` is used in a design where the system clock is relatively
slow and the minimum CS high time is known for a specific flash chip, it
can be desirable to pass in a cs_delay lower than 10.
For example, with a system clock of 75MHz and using GD25LQ128D which
specifies 20ns minimum CS high time, the delay can be satisfied in only
2 clock cycles instead of 10. This gives a slight throughput improvement
for non-sequential access to flash.
=> phy/generic: make minimum CS inactive time configurable

litespi/modules/modules.py, litespi/opcodes.py, litespi/phy/generic.py
Currently LiteSPI can't send commands using 4 lines (e.g. in QPI mode). This PR enables that and adds an SPI flash chip that supports the new `READ_4_4_4` opcode.
=> Support command width of 4 (READ_4_4_4)

litespi/__init__.py, litespi/clkgen.py, litespi/core/mmap.py, litespi/crossbar.py, litespi/phy/ddr_generic.py, litespi/phy/generic.py, litespi/phy/legacy_generic.py, litespi/phy/model.py, test/test_spi_mmap.py
With this PR the litespi:
- has simplified PHY core. CMD and USER states have been reimplemented as USER state in MMAP core.
- implements the PHY using the ODDR/IDDR cores.
We updated the model.py and tests so they are compatible with new implementation.
Litex PR related to this change can be found under this : https://github.com/enjoy-digital/litex/pull/1024
=> Litespi - using the ODDR/IDDR, simplifying models 

litespi/core/mmap.py, litespi/phy/generic.py, litespi/phy/generic_ddr.py
This PR reverts 2 optimizations that were added in #57, It turns out that this version of the MMAP/PHY logic fails on the Crosslink-NX platform (there might be other compatibility issues and I think reverting those commits is the best option for now). This also adds parameter for compensating for  additional latency if needed - setting it to `1` on Crosslink-NX was required to get correct results.
=> Fix DDR PHY compatibility with Crosslink-NX

litespi/__init__.py, litespi/core/mmap.py
Dropping the dummy_bits CSR can help to save area in very congested
designs.
=> mmap: make CSR optional

litespi/phy/generic_sdr.py
Useful for qspi master-only operation, example integration below:
from litespi.phy.generic import LiteSPIPHY
qspi_pads = self.platform.request("qspi1")
qspi_phy = LiteSPIPHY(qspi_pads, None, device=self.platform.device)
self.add_module(name="qspi_phy", module=qspi_phy)
from litespi import LiteSPI
qspi_core = LiteSPI(qspi_phy, with_mmap=False)
self.add_module(name="qspi_core", module=qspi_core)
=> SDRPHY: support flash=None

litespi/__init__.py, litespi/core/mmap.py, test/test_spi_mmap.py
With this change, it is possible to memory map e.g. PSRAM. When setting with_write to "csr", it can also be used to support faster flash writing via etherbone. For flash, only False and "csr" should be used, as the some other logic or application needs to make sure that the flash is erased ahead of time. True is only meant for use with RAM chips.
There are two bugs that this also addresses:
1. ~~Addresses are now masked to flash size or addr_width if no size is set. I'm not 100% happy with this solution, as it might cause issues with non power of 2 flashes (do those exist). However, without this, I would get flash writes to the wishbone address rather than offsets inside the flash. So I'm open to better alternatives. Optimum would be subtracting the base bus address, but I haven't found …
=> mmap: Add write functionality

litespi/core/mmap.py, litespi/modules/__init__.py, litespi/modules/modules.py, litespi/modules/ram_modules.py, litespi/opcodes.py, litespi/spi_nor_flash_module.py
ths commit fixes the dummy bits calculation in the litespi core.
The dummy bits are now calculated correctly based on dummy cyles
and these are now correctly set in the spi_nor_flash_module.
THis also lets you add a dict to the flash module named dummy_cycles, where the amount of cycles can be set for each op code.
=> core: mmap.py: fix dummy bits

litespi/modules/generated_modules.py, litespi/spi_nor_flash_module.py
@enjoy-digital 
If more that one module is used with incompatible read_cmds, it leads to a a raised ValueError (Read command ... not supported in chip ...).
This fixes it so the different modules wont share a common read_cmds array if that is not explicitly defined.
also adds modes for the W25Q128JV.
=> spi_nor_flash_module.py: fix read_cmds array

litespi/clkgen.py, litespi/phy/generic_ddr.py, litespi/phy/generic_sdr.py
@enjoy-digital 
this removes some unused variables and stuff that was used with dtr flash modes, which are already no longer supported.
=> phy: cleanup

litespi/__init__.py, litespi/clkgen.py, litespi/core/master.py, litespi/core/mmap.py, litespi/gen.py, litespi/phy/generic.py, litespi/phy/generic_ddr.py, litespi/phy/generic_sdr.py
@enjoy-digital 
move to LiteXModule
=> move to LiteXModule

litespi/core/mmap.py, test/test_spi_mmap.py
remove offset logic, this is now handled centrally here:
https://github.com/enjoy-digital/litex/pull/2166
By the way, the former implementation for the offset was done wrong.
That offset was applied to the wishbone `adr` only, but it should have been shifted by 2,
as it is word aligned.
``source.data.eq(Cat(byte_count, bus.adr - offset)),`` should have been ``source.data.eq(Cat(byte_count, bus.adr) - offset),``
=> mmap: remove offset logic
